[common] 네비게이션 바 컴포넌트
DeliverBle/deliverble-frontend pull request #13
Opened 2022-07-12 19:34 UTC by choichoijin

## 🚩 관련 이슈
- close #6 

## 📋 작업 내용
- [x] 기능 구현
- [x] 페이지 구조화 및 스타일링
- [x] 페이지별 버튼(Tab) 스타일링

## 📌 PR Point
- common 폴더 내에 NavigationBar 컴포넌트를 구현했습니다. 
- router.pathname으로 페이지를 구분하기 위해 className을 사용했는데 괜찮은 방법일까요?
저는 clicked를 썼는데 네이밍도 고민이에요
- 일단 로그인 부분 이미지는 따로 전환되도록 구현하지 않았습니다. 

## 📸 스크린샷

https://user-images.githubusercontent.com/99077953/178578605-3f48aaa3-abba-4ae5-bc6d-f35ab4e186fa.mov

2022-07-13 05:33 UTC, songah119 approved these changes
첫 피알 축하합니당 우리 남은 것도 열심히 해봐요><

2022-07-13 05:33 UTC, songah119 commented on src/components/common/NavigationBar.tsx
> +  position: sticky;
저는 navigation바 디자인 할 때, position fixed 썼는데, 궁금해서 찾아보니까 
둘의 차이점이 좀 있는 것 같아요! 저희의 경우에는 navbar 가 맨위에 고정되어 있어서 둘 다 사용해도 될 것 같지만, 
참고하시라고 링크 첨부합니다!
https://www.geeksforgeeks.org/what-is-the-difference-between-positionsticky-and-positionfixed-in-css/
다른 분들은 어떻게 생각하는 지 궁금해요!

2022-07-13 05:52 UTC, choichoijin commented on src/components/common/NavigationBar.tsx
> +
저는 이 a 태그 부분에 cursor: pointer를 주지 않았는데 pointer로 작동이 되어요..! 혹시 왜 그런지 아시는 분 있을까요??

2022-07-13 06:05 UTC, choichoijin commented on src/components/common/NavigationBar.tsx
> +  position: sticky;
position: sticky와 fixed의 차이로 공간 차지 여부가 있다고 알고있어요! fixed를 하게 될 경우 네비게이션 바가 레이아웃에 영향을 미치지 않아, 하단에 페이지 내용이 네비게이션 바 밑에 있는 것처럼 나와서 sticky로 설정하게 되었습니당
랜딩페이지의 경우에는 배경이 보여야 하니까 저는 fixed 잘 사용하신 것 같다고 생각해요 🙆🏻‍♀️

2022-07-13 07:01 UTC, songah119 commented on src/components/common/NavigationBar.tsx
> +
a 태그는 href로 링크를 주면 자동적으로 커서가 포인터로 바뀐다고 알고있습니다!

2022-07-13 07:03 UTC, solar3070 approved these changes

2022-07-13 07:03 UTC, solar3070 commented on src/styles/globalStyle.ts
>      color: ${COLOR.BLACK};
:visited 가상옵션을 지워주신 이유가 궁금합니다.

2022-07-13 07:08 UTC, 100Gyeon requested changes

2022-07-13 07:08 UTC, 100Gyeon commented on src/components/common/NavigationBar.tsx
> +          </StTab>
```suggestion
          <StTab isActive={router.pathname === '/home'}>
            <Link href="/home">
              <a>홈</a>
            </Link>
          </StTab>
          <StTab isActive={router.pathname === '/learn'}>
            <Link href="/learn">
              <a>학습하기</a>
            </Link>
          </StTab>
          <StTab isActive={router.pathname === '/review'}>
            <Link href="/review">
              <a>복습하기</a>
            </Link>
          </StTab>
```

className 대신 props를 활용하면 더 좋을 것 같네요! 😊

2022-07-13 07:08 UTC, 100Gyeon commented on src/components/common/NavigationBar.tsx
> +const StTab = styled.li`
```suggestion
const StTab = styled.li<{ isActive: boolean }>`
```

위에서 사용한 isActive는 이렇게 받아올 수 있습니다~!

2022-07-13 07:08 UTC, 100Gyeon commented on src/components/common/NavigationBar.tsx
> +`;
```suggestion
  ${({ isActive }) =>
    isActive &&
    css`
      border-bottom: 0.3rem solid transparent;
      border-image: linear-gradient(45deg, ${COLOR.SUB_PURPLE}, ${COLOR.MAIN_BLUE});
      border-image-slice: 1;
      & > a {
        color: ${COLOR.BLACK};
        ${FONT_STYLES.SB_24_HEADLINE};
      }
    `}
`;
```

className 대신 isActive를 사용하면 이렇게 바꿀 수 있어요!

2022-07-13 07:08 UTC, 100Gyeon commented on src/pages/index.tsx
> +      <div>Home</div>
여기는 랜딩 페이지니까 지워주셔도 됩니당 !!

2022-07-13 07:08 UTC, 100Gyeon commented on src/pages/index.tsx
> +  height: 5000rem;
스크롤 될 때 네비게이션 바가 위에 고정되는지 보려고 5000rem으로 한 것 같은데 맞나용?
맞다면 머지하기 전에 원래대로 값 바꿔주세요 !!

2022-07-13 07:09 UTC, 100Gyeon commented on src/components/common/NavigationBar.tsx
> +      <ImageDiv className="logo" priority src={imgLogo} layout="fill" alt="" />
여기 DeliverBle 넣어주세용 !!

2022-07-13 07:12 UTC, solar3070 commented on src/components/common/NavigationBar.tsx
> +          </StTab>
깔끔하다!!

2022-07-13 10:28 UTC, choichoijin commented on src/components/common/NavigationBar.tsx
> +      <ImageDiv className="logo" priority src={imgLogo} layout="fill" alt="" />
넵!

2022-07-13 10:32 UTC, choichoijin commented on src/styles/globalStyle.ts
>      color: ${COLOR.BLACK};
a:visited에 기본으로 설정된 색상 때문에, 방문했던 기록이 있는 페이지로 이동하는 a태그 색깔이 고정이 되더라구요! 그래서 삭제해주었습니다

2022-07-13 10:33 UTC, choichoijin commented on src/components/common/NavigationBar.tsx
> +      <ImageDiv className="logo" priority src={imgLogo} layout="fill" alt="" />
기획에 물어봤더니 홈으로 가는 기능이 있다고 하셔서 추가하겠습니다!

2022-07-13 10:33 UTC, choichoijin commented on src/components/common/NavigationBar.tsx
> +          </StTab>
좋아요!! 수정하겠습니다

2022-07-13 10:34 UTC, choichoijin commented on src/pages/index.tsx
> +  height: 5000rem;
테스트로 확인했던게 그대로 들어갔네요 😅 삭제하겠습니당

2022-07-14 05:15 UTC, 100Gyeon approved these changes

2022-07-14 05:19 UTC, merged